#!/bin/bash
#created by: Anastasios Daskalakis
#You need pyenv and virtual Env before running this code
module load connectome-workbench #Load connectome work bench in order to run ciftify
PipeDir=/archive/data/NEUR/pipelines/bids_apps/ #the directory that stores all of your raw data
#This shouldnt change, but its defining the location of the ciftify container
ciftify_container=/archive/code/containers/FMRIPREP_CIFTIFY/tigrlab_fmriprep_ciftify_1.1.2-2.1.0-2018-10-12-dcfba6cc0add.img
#The output directory that you want store your files into
OutputDir=/projects/adaskalakis/NEUR/fMRI/

#This goes into your your raw data directory and goes into the ciftify folder (all folders should have common subfiles)
cd ${PipeDir}/ciftify
#Start of a forloop that looks for foles that begin with the name "sub" and tries to load them
for subject in sub-*
do
  #defines the path past those subjects that you just loaded into the actual data
  input_path=${PipeDir}/ciftify/${subject}/MNINonLinear/

  #loads the Json file
  json=/projects/adaskalakis/NEUR/fMRI/neur_rest_cleanFD_filter_smooth.json  #json file location goes here
  #once it has all been loaded, it will make a file in your output directory for all the cleaned files
  mkdir ${OutputDir}/${subject}_${func_base}

#nested loop that goes though the !3! scans that we did for this study, if you did more extend those numbers... less will give you errors but code will run
for run in 1 2 3
do
   #will show you which subject file is currently loaded and running
  echo $subject $run
  #loads the specific TSV file for that data file 
  confounds=${PipeDir}/fmriprep/${subject}/ses-01/func/${subject}_ses-01_task-rest_acq-CMH_run-0${run}_desc-confounds_regressors.tsv

  #Runs through the specific parameters ciftify requires to work
  ciftify_clean_img --clean-config=${json} \
    --confounds-tsv=${confounds} \
    --output-file=${OutputDir}/${subject}_${func_base}_Atlas_s0_clean.dtseries.nii \
    --left-surface=${input_path}/fsaverage_LR32k/${subject}.L.midthickness.32k_fs_LR.surf.gii \
    --right-surface=${input_path}/fsaverage_LR32k/${subject}.R.midthickness.32k_fs_LR.surf.gii \
    ${input_path}/Results/ses-01_task-rest_acq-CMH_run-0${run}_desc-preproc/ses-01_task-rest_acq-CMH_run-0${run}_desc-preproc_Atlas_s0.dtseries.nii

    done
done
